all:
		gcc SocketServer.c -o SocketServer
		gcc SocketClient.c -o SocketClient
debug:
		gcc -g SocketServer.c -o SocketServer
		gcc -g SocketClient.c -o SocketClient
clean:
		rm SocketServer SocketClient
