all:
		gcc -O SocketServer.c -o SocketServer
		gcc -O SocketClient.c -o SocketClient
debug:
		gcc -g SocketServer.c -o SocketServer
		gcc -g SocketClient.c -o SocketClient
clean:
		rm SocketServer SocketClient
